apiVersion: v1
kind: Service
metadata:
  name: todo-frontend
  labels:
    app: todo-frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
  - port: {{ .Values.frontend.service.port }}
    targetPort: 3000
    nodePort: {{ .Values.frontend.service.nodePort }}
    protocol: TCP
  selector:
    app: todo-frontend
